package com.lightresearch.probecamera.ausbc.utils


import android.util.SparseArray

object USBVendorId {
    private val IDS = SparseArray<String>()
    fun vendorName(vendor_id: Int): String {
        return IDS[vendor_id]
    }

    init {
        IDS.put(10006, "YUEN DA ELECTRONIC PRODUCTS FACTORY")
        IDS.put(10013, "Gionee Communication Equipment Co., Ltd. ShenZhen")
        IDS.put(10022, "Universal Electronics Inc. (dba: TVIEW)")
        IDS.put(1003, "Atmel Corporation")
        IDS.put(1006, "Mitsumi")
        IDS.put(1008, "HP Inc.")
        IDS.put(10112, "M31 Technology Corp.")
        IDS.put(10113, "Liteconn Co., Ltd.")
        IDS.put(10121, "Suzhou WEIJU Electronics Technology Co., Ltd.")
        IDS.put(10144, "Mondokey Limited")
        IDS.put(10149, "Advantest Corporation")
        IDS.put(10150, "iRobot Corporation")
        IDS.put(1020, "Elitegroup Computer Systems")
        IDS.put(1021, "Xilinx Inc.")
        IDS.put(10226, "Sibridge Tech.")
        IDS.put(1026, "ALi Corporation")
        IDS.put(1027, "Future Technology Devices International Limited")
        IDS.put(10275, "Dongguan Jiumutong Industry Co., Ltd.")
        IDS.put(10289, "Power Integrations")
        IDS.put(10291, "Oculus VR, Inc.")
        IDS.put(10300, "HIGH TEK HARNESS ENTERPRISE CO., LTD.")
        IDS.put(10316, "Full in Hope Co., Ltd.")
        IDS.put(1032, "Quanta Computer Inc.")
        IDS.put(10329, "Viconn Technology (HK) Co., Ltd.")
        IDS.put(1033, "NEC Corporation")
        IDS.put(1035, "Weltrend Semiconductor")
        IDS.put(1037, "VIA Technologies, Inc.")
        IDS.put(10374, "Seeed Technology Co., Ltd.")
        IDS.put(10375, "Specwerkz")
        IDS.put(1038, "MCCI Corporation")
        IDS.put(10398, "Esselte Leitz GmbH & Co. KG")
        IDS.put(10406, "E-SEEK Inc.")
        IDS.put(1041, "BUFFALO INC.")
        IDS.put(10423, "Pleora Technologies Inc.")
        IDS.put(10431, "Vitetech Int'l Co., Ltd.")
        IDS.put(1044, "Giga-Byte Technology Co., Ltd.")
        IDS.put(10446, "Changzhou Shi Wujin Miqi East Electronic Co., Ltd.")
        IDS.put(10457, "Shenzhen Ourconn Technology Co., Ltd.")
        IDS.put(10458, "G.SKILL Int'l Enterprice Co., Ltd.")
        IDS.put(1046, "Nuvoton Technology Corp.")
        IDS.put(10466, "Surplus Electronic Technology Co., Ltd.")
        IDS.put(10470, "BIAMP SYSTEMS")
        IDS.put(10509, "IBCONN Technologies (Shenzhen) Co., Ltd.")
        IDS.put(10510, "Fugoo Inc.")
        IDS.put(10519, "Pan Xin Precision Electronics Co., Ltd.")
        IDS.put(10530, "Dongguan Digi-in Digital Technology Co., Ltd.")
        IDS.put(1054, "Creative Labs")
        IDS.put(10540, "GENUSION, Inc.")
        IDS.put(10544, "Ineda Systems Inc.")
        IDS.put(10545, "Jolla Ltd.")
        IDS.put(10546, "Peraso Technologies, Inc.")
        IDS.put(10549, "Nanjing Magewell Electronics Co., Ltd.")
        IDS.put(10560, "Shenzhen Yiwanda Electronics Co., Ltd.")
        IDS.put(1057, "Nokia Corporation")
        IDS.put(10575, "Dollar Connection Ltd.")
        IDS.put(10595, "BIO-key International, Inc.")
        IDS.put(1060, "Microchip-SMSC")
        IDS.put(10603, "Xacti Corporation")
        IDS.put(10615, "Shenzhen Zowee Technology Co., Ltd.")
        IDS.put(10643, "ADPlaus Technology Limited")
        IDS.put(10646, "Unwired Technology")
        IDS.put(1065, "Cirrus Logic Inc.")
        IDS.put(10657, "Union Electric Plug & Connector Corp.")
        IDS.put(10674, "Canova Tech")
        IDS.put(10685, "Silicon Works")
        IDS.put(10695, "HANRICO ANFU ELECTRONICS CO., LTD.")
        IDS.put(10700, "Kodak Alaris")
        IDS.put(10702, "JGR Optics Inc.")
        IDS.put(10703, "Richtek Technology Corporation")
        IDS.put(10705, "Binatone Electronics Int. Ltd.")
        IDS.put(1071, "Molex Inc.")
        IDS.put(10715, "Shenzhen iBoard Technology Co., Ltd.")
        IDS.put(10719, "SMIT(HK) Limited")
        IDS.put(1072, "Fujitsu Component Limited")
        IDS.put(10725, "Dongguan Kechenda Electronic Technology Co., Ltd.")
        IDS.put(10726, "Fengshun Peiying Electro-Acoustic Co., Ltd.")
        IDS.put(10744, "MD ELEKTRONIK GmbH")
        IDS.put(10749, "Bad Elf, LLC")
        IDS.put(10770, "Vreo Limited")
        IDS.put(10772, "Kanex")
        IDS.put(10781, "Oxford Nanopore Technologies")
        IDS.put(10782, "Obsidian Technology")
        IDS.put(10783, "Lucent Trans Electronics Co., Ltd.")
        IDS.put(10784, "GUOGUANG GROUP CO., LTD.")
        IDS.put(10788, "CNPLUS")
        IDS.put(10789, "Fourstar Group")
        IDS.put(10790, "Tragant International Co., Ltd.")
        IDS.put(10791, "DongGuan LianGang Optoelectronic Technology Co., Ltd.")
        IDS.put(10797, "Atrust Computer Corp.")
        IDS.put(10798, "VIA Alliance Semiconductor Co., Ltd.")
        IDS.put(10799, "BSUN Electronics Co., Ltd.")
        IDS.put(1080, "Advanced Micro Devices")
        IDS.put(10807, "RTD Embedded Technologies, Inc.")
        IDS.put(10816, "Shenzhen Choseal Industrial Co., Ltd.")
        IDS.put(10817, "Canyon Semiconductor")
        IDS.put(10818, "Spectra7 Microsystems Corp.")
        IDS.put(10821, "Meizu Technology Co., Ltd.")
        IDS.put(10822, "Hubei Yingtong Telecommunication Cable Inc.")
        IDS.put(10829, "Wilder Technologies")
        IDS.put(10837, "Diodes Inc.")
        IDS.put(10846, "DuPont")
        IDS.put(1085, "Lexmark International Inc.")
        IDS.put(10852, "Zhejiang Songcheng Electronics Co., Ltd.")
        IDS.put(10859, "VSN Mobil")
        IDS.put(10875, "Bellwether Electronic Corp.")
        IDS.put(10878, "VAIO Corporation")
        IDS.put(10879, "Perixx Computer GmbH")
        IDS.put(10885, "HANK ELECTRONICS CO., LTD")
        IDS.put(10892, "Sonnet Technologies, Inc.")
        IDS.put(10893, "Keysight Technologies Inc.")
        IDS.put(10895, "Manutronics Vietnam Joint Stock Company")
        IDS.put(10900, "G2 Touch Co., Ltd.")
        IDS.put(10902, "Micromax Informatics Ltd")
        IDS.put(10910, "SEIKO SOLUTIONS Inc.")
        IDS.put(10912, "Casco Products Corp.")
        IDS.put(10922, "Virtium Technology, Inc.")
        IDS.put(10923, "Field and Company LLC, dba Leef USA")
        IDS.put(10928, "GM Global Technology Operations LLC")
        IDS.put(10931, "Key Asic Inc.")
        IDS.put(10943, "Revolabs, Inc.")
        IDS.put(10945, "Lattice Semiconductor Corp")
        IDS.put(10947, "Foshan Nanhai Saga Audio Equipment Co., Ltd.")
        IDS.put(10957, "Silergy Corp.")
        IDS.put(10963, "Shenzhen Hali-Power Industrial Co., Ltd.")
        IDS.put(10971, "I-PEX (Dai-ichi Seiko)")
        IDS.put(10973, "SEE-PLUS INDUSTRIAL LTD.")
        IDS.put(10990, "Adapt-IP Company")
        IDS.put(10997, "Libratone A/S")
        IDS.put(10999, "Shenzhen Hazens Automotive Electronics (SZ) Co., Ltd.")
        IDS.put(11000, "Jiangsu Toppower Automotive Electronics Co., Ltd.")
        IDS.put(11001, "Drapho Electronics Technology Co., Ltd.")
        IDS.put(1102, "Alps Electric Co., Ltd.")
        IDS.put(11022, "Le Shi Zhi Xin Electronic Technology (Tian Jin) Limited")
        IDS.put(11024, "Cardiac Insight, Inc.")
        IDS.put(11028, "EverPro Technologies Company, Ltd.")
        IDS.put(11029, "Rosenberger Hochfrequenztechnik")
        IDS.put(11035, "Dongguan City Sanji Electronics Co., Ltd.")
        IDS.put(11037, "Lintes Technology Co., Ltd.")
        IDS.put(11039, "KinnexA, Inc.")
        IDS.put(11042, "Metra Electronics Corp.")
        IDS.put(11044, "KeepKey, LLC")
        IDS.put(11047, "FluxData Incorporated")
        IDS.put(1105, "Texas Instruments")
        IDS.put(11061, "Assem Technology Co., Ltd.")
        IDS.put(11062, "Dongguan City Jianghan Electronics Co., Ltd.")
        IDS.put(11063, "Huizhou Desay SV Automotive Co., Ltd.")
        IDS.put(11064, "Ningbo Rixing Electronics Co., Ltd.")
        IDS.put(11069, "GuangDong YuanFeng Automotive Electroics Co., Ltd.")
        IDS.put(11080, "Sounding Audio Industrial Limited")
        IDS.put(11082, "Yueqing Huaxin Electronic Co., Ltd.")
        IDS.put(11098, "Universal Audio, Inc.")
        IDS.put(11111, "Lifesize, Inc.")
        IDS.put(11123, "Pioneer DJ Corporation")
        IDS.put(11124, "Embedded Intelligence, Inc.")
        IDS.put(11125, "New Matter")
        IDS.put(11126, "Shanghai Wingtech Electronic Technology Co., Ltd.")
        IDS.put(11127, "Epiphan Systems Inc.")
        IDS.put(11130, "Spin Master Far East Ltd.")
        IDS.put(11131, "Gigaset Digital Technology (Shenzhen) Co., Ltd.")
        IDS.put(11132, "Noveltek Semiconductor Corp.")
        IDS.put(11139, "Silicon Line GmbH")
        IDS.put(11140, "Ever Win International Corp.")
        IDS.put(11144, "Socionext Inc.")
        IDS.put(11145, "Ugreen Group Limited")
        IDS.put(11146, "Shanghai Pateo Electronic Equipment Mfg. Co., Ltd.")
        IDS.put(1115, "Renesas Electronics Corp.")
        IDS.put(11154, "i-BLADES, Inc.")
        IDS.put(11155, "Altia Systems Inc.")
        IDS.put(11156, "ShenZhen Baoyuanda Electronics Co., Ltd.")
        IDS.put(11157, "iST - Integrated Service Technology Inc.")
        IDS.put(11158, "HYUNDAI MOBIS Co., Ltd.")
        IDS.put(11161, "360fly, Inc.")
        IDS.put(11162, "HUIZHOU CHENG SHUO HARDWARE PLASTIC CO., LTD.")
        IDS.put(11163, "Zhongshan Aute Electronics Technology Co., Ltd.")
        IDS.put(11164, "Guangdong King Link Industrial Co., Ltd.")
        IDS.put(11167, "Scietera Technologies, Inc.")
        IDS.put(11168, "InVue Security Products")
        IDS.put(11169, "I-Sheng Electric Wire & Cable Co., Ltd.")
        IDS.put(11170, "China Daheng Group Inc Beijing Image Vision Tech Branch")
        IDS.put(11171, "Shenzhen FeiTianXia Technology Ltd.")
        IDS.put(11172, "Shenzhen HengJia New Energy Auto Part Co., Ltd.")
        IDS.put(11175, "77 Elektronika Kft.")
        IDS.put(11176, "YUDU EASON ELECTRONIC CO., LTD.")
        IDS.put(1118, "Microsoft Corporation")
        IDS.put(11181, "XIN JI (SHENZHEN) COMPUTER PARTS CO., LTD.")
        IDS.put(11189, "Silk ID Systems")
        IDS.put(11190, "3D Imaging & Simulations Corp. (3DISC)")
        IDS.put(11191, "Dongguan ChengXiang Industrial Co., Ltd.")
        IDS.put(11192, "OCC (Zhuhai) Electronic Co., Ltd.")
        IDS.put(11194, "Sinseader Electronic Co., Ltd.")
        IDS.put(11195, "DONGGUAN YELLOWKNIFE Industrial Co., Ltd.")
        IDS.put(11197, "RF Creations Ltd.")
        IDS.put(11198, "Chengyi Semiconductors (Shanghai) Co., Ltd.")
        IDS.put(11199, "Shenzhen Shinning Electronic Co., Ltd.")
        IDS.put(11200, "Shenzhen WFD Electronics Co., Ltd.")
        IDS.put(11201, "Dongguan Sino Syncs Industrial Co., Ltd.")
        IDS.put(11202, "JNTC Co., Ltd.")
        IDS.put(11208, "DONGGUAN POLIXIN ELECTRIC CO., LTD.")
        IDS.put(11209, "Tama Electric (Suzhou) Co., Ltd.")
        IDS.put(1121, "Primax Electronics")
        IDS.put(11210, "Exvision, Inc.")
        IDS.put(11216, "mophie, LLC")
        IDS.put(11219, "Dongguan ULT-unite electronic technology co., LTD")
        IDS.put(11220, "JL Audio, Inc.")
        IDS.put(11221, "Cable Matters Inc.")
        IDS.put(11222, "CoroWare, Inc.")
        IDS.put(11229, "Charm Sciences Inc.")
        IDS.put(1123, "EATON")
        IDS.put(11230, "Pickering Interfaces Limited")
        IDS.put(11231, "Hangzhou Hikvision Digital Technology Co., Ltd.")
    }
}